USE [AIDE]
GO

/****** Object:  Table [dbo].[ASSETS]    Script Date: 07/07/2019 8:52:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF NOT EXISTS(SELECT (1) FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'ASSETS' AND [COLUMN_NAME] = 'PREVIOUS_ID')
	BEGIN
		ALTER TABLE [DBO].[ASSETS]
		ADD PREVIOUS_ID INT NULL
	END

IF NOT EXISTS(SELECT (1) FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'ASSETS' AND [COLUMN_NAME] = 'BORROW_FG')
	BEGIN
		ALTER TABLE [DBO].[ASSETS]
		ADD BORROW_FG INT NULL DEFAULT(0) WITH VALUES
	END

IF NOT EXISTS(SELECT (1) FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'ASSETS' AND [COLUMN_NAME] = 'BORROW_STATUS')
	BEGIN
		ALTER TABLE [DBO].[ASSETS]
		ADD BORROW_STATUS INT NULL DEFAULT(0) WITH VALUES
	END

GO

SET ANSI_PADDING OFF
GO


