USE [AIDE]
GO

/****** Object:  Table [dbo].[ATTENDANCE]    Script Date: 09/02/2019 1:53:26 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER TABLE ATTENDANCE
ADD LOGOFF_FLG TINYINT
	CONSTRAINT df_Logoff_flg DEFAULT(0) WITH VALUES,
	LOGOFF_TIME DATETIME
	
GO


