USE [AIDE]
GO

/****** Object:  Table [dbo].[WEEKLY_REPORT]    Script Date: 09/02/2019 1:53:26 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS(SELECT (1) FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'WEEKLY_REPORT' AND [COLUMN_NAME] = 'WR_TASK_ID')
	BEGIN
		ALTER TABLE WEEKLY_REPORT 
		ADD WR_TASK_ID INT
	END

IF EXISTS(SELECT (1) FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'WEEKLY_REPORT' AND [COLUMN_NAME] = 'WR_DELETE_FG')
	BEGIN
		ALTER TABLE WEEKLY_REPORT 
		DROP CONSTRAINT WEEKLY_DELETE_COL

		ALTER TABLE WEEKLY_REPORT 
		DROP COLUMN WR_DELETE_FG

		ALTER TABLE WEEKLY_REPORT 
		ADD WR_DELETE_FG SMALLINT
		CONSTRAINT WEEKLY_DELETE_COL DEFAULT(0) WITH VALUES
	END
ELSE
	BEGIN
		ALTER TABLE WEEKLY_REPORT 
		ADD WR_DELETE_FG SMALLINT
		CONSTRAINT WEEKLY_DELETE_COL DEFAULT(0) WITH VALUES
	END

GO


