USE [AIDE]
GO

/****** Object:  Table [dbo].[ASSETS]    Script Date: 07/07/2019 8:52:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

IF NOT EXISTS(SELECT (1) FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'ANNOUNCEMENTS' AND [COLUMN_NAME] = 'DELETED_FG')
	BEGIN
		ALTER TABLE [DBO].[ANNOUNCEMENTS]
		ADD DELETED_FG INT DEFAULT (0) WITH VALUES
	END
GO

SET ANSI_PADDING OFF
GO


