USE [AIDE]
GO

/****** Object:  Table [dbo].[ASSETS]    Script Date: 07/07/2019 8:52:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

ALTER TABLE [DBO].[ASSETS]
	ADD PREVIOUS_ID INT NULL
GO

ALTER TABLE [DBO].[ASSETS]
	ADD BORROW_FG INT NULL DEFAULT(0)
GO

ALTER TABLE [DBO].[ASSETS]
	ADD BORROW_STATUS INT NULL DEFAULT(0)
GO

SET ANSI_PADDING OFF
GO


