USE [AIDE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PROBLEM')
BEGIN
	DROP TABLE [dbo].[PROBLEM]
END

CREATE TABLE [dbo].[PROBLEM](
	[PROBLEM_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMP_ID] [int] NOT NULL,
	[PROBLEM_DESCR] VARCHAR(MAX),
	[PROBLEM_INVOLVE] VARCHAR(MAX)
	
 CONSTRAINT [PK_PROBLEM] PRIMARY KEY CLUSTERED 
(
	[PROBLEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


