USE [AIDE]
GO

/****** Object:  Table [dbo].[KPI_TARGETS]    Script Date: 9/12/2019 8:56:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KPI_TARGETS')
BEGIN
	DROP TABLE [dbo].[KPI_TARGETS]
END
CREATE TABLE [dbo].[KPI_TARGETS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FY_START] [date] NOT NULL,
	[FY_END] [date] NOT NULL,
	[KPI_REF] [varchar](20) NOT NULL,
	[SUBJECT] [varchar](50) NOT NULL,
	[DESCRIPTION] [varchar](max) NOT NULL,
	[DATE_CREATED] [date] NOT NULL,
 CONSTRAINT [PK_KPI_TARGETS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[FY_START] ASC,
	[FY_END] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


