USE [AIDE]
GO

/****** Object:  Table [dbo].[WORKPLACE_AUDIT_SCHEDULE]    Script Date: 04/06/2020 5:09:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'WORKPLACE_AUDIT_SCHEDULE')
BEGIN
	DROP TABLE [dbo].[WORKPLACE_AUDIT_SCHEDULE]
END
CREATE TABLE [dbo].[WORKPLACE_AUDIT_SCHEDULE](
	[AUDIT_SCHED_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMP_ID] [int] NULL,
	[FY_WEEK] [int] NOT NULL,
	[PERIOD_START] [date] NOT NULL,
	[PERIOD_END] [date] NOT NULL,
	[DAILY] [varchar](15) NOT NULL,
	[WEEKLY] [varchar](15) NOT NULL,
	[MONTHLY] [varchar](15) NOT NULL,
	[FY_START] [date] NOT NULL,
	[FY_END] [date] NOT NULL,
 CONSTRAINT [PK_AUDIT_SCHED_ID] PRIMARY KEY CLUSTERED 
(
	[AUDIT_SCHED_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


