USE [AIDE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DIVISION')
BEGIN
	DROP TABLE [dbo].[DIVISION]
END
CREATE TABLE [dbo].[DIVISION](
	[DEPT_ID] [smallint] NOT NULL,
	[DIV_ID] [smallint] NOT NULL,
	[DESCR] [varchar](50) NULL,
 CONSTRAINT [PK_DIVISION] PRIMARY KEY CLUSTERED 
(
	[DEPT_ID] ASC,
	[DIV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


