USE [AIDE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PROBLEM_SOLUTION')
BEGIN
	DROP TABLE [dbo].[PROBLEM_SOLUTION]
END

CREATE TABLE [dbo].[PROBLEM_SOLUTION](
	[SOLUTION_ID] [int] IDENTITY(1,1) NOT NULL,
	[PROBLEM_ID] [int] NOT NULL,
	[OPTION_ID] [int] NOT NULL,
	[SOLUTION_DESCR] VARCHAR(MAX)
 CONSTRAINT [PK_PROBLEM_SOLUTION] PRIMARY KEY CLUSTERED 
(
	[SOLUTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


