USE [AIDE]
GO

/****** Object:  Table [dbo].[WORKPLACE_AUDIT_DAILY]    Script Date: 9/12/2019 8:56:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'WORKPLACE_AUDIT_DAILY')
BEGIN
	DROP TABLE [dbo].[WORKPLACE_AUDIT_DAILY]
END

CREATE TABLE [dbo].WORKPLACE_AUDIT_DAILY(
	[AUDIT_DAILY_ID] [int] IDENTITY(1,1) NOT NULL,
	[AUDIT_QUESTIONS_ID] [int] NOT NULL,
	[EMP_ID] [int] NOT NULL,
	[FY_WEEK] [int] NOT NULL,
	[DT_CHECKED] [datetime] NULL,
	[DT_CHECK_FLG] [int] NULL,
	[WEEKDATE] [date] NULL,
 CONSTRAINT [PK_WORKPLACE_AUDIT_DAILY] PRIMARY KEY CLUSTERED 
(
	[AUDIT_DAILY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


