USE [AIDE]
GO

/****** Object:  Table [dbo].[REPORTS]    Script Date: 9/13/2019 10:42:40 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'REPORTS')
BEGIN
	DROP TABLE [dbo].[REPORTS]
END
GO

CREATE TABLE [dbo].[REPORTS](
	[REPORT_ID] [int] IDENTITY(1,1) NOT NULL,
	[OPT_ID] [int] NOT NULL,
	[MODULE ID] [int] NOT NULL,
	[DESCRIPTION] [text] NULL,
	[VALUE] [text] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[REPORT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


GO

