USE [AIDE]
GO

/****** Object:  Table [dbo].[KPI_SUMMARY]    Script Date: 9/13/2019 10:42:40 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'KPI_SUMMARY')
BEGIN
	DROP TABLE [dbo].[KPI_SUMMARY]
END
GO
CREATE TABLE [dbo].[KPI_SUMMARY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EMP_ID] [int] NOT NULL,
	[KPI_REF] [nvarchar](15) NOT NULL,
	[FY_START] [date] NOT NULL,
	[FY_END] [date] NOT NULL,
	[KPI_MONTH] [smallint] NOT NULL,
	[KPI_TARGET] [float] NULL,
	[KPI_ACTUAL] [float] NULL,
	[KPI_OVERALL] [float] NULL,
	[DATE_POSTED] datetime NULL
 CONSTRAINT [PK_KPI_SUMMARY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[EMP_ID] ASC,
	[KPI_REF] ASC,
	[FY_START] ASC,
	[FY_END] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


