USE [AIDE]
GO

/****** Object:  Table [dbo].[FISCAL_YEAR] ******/
SET ANSI_NULLS ON
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FISCAL_YEAR')
BEGIN
	DROP TABLE [dbo].[FISCAL_YEAR]
END

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FISCAL_YEAR](
	[ID] [nvarchar](6) NOT NULL,
	[FY_START] [date] NOT NULL,
	[FY_END] [date] NOT NULL,
 CONSTRAINT [PK_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


