USE [AIDE]
GO

/****** Object:  Table [dbo].[WORKPLACE_AUDIT_OWNER]    Script Date: 9/12/2019 8:56:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'WORKPLACE_AUDIT_OWNER')
BEGIN
	DROP TABLE [dbo].[WORKPLACE_AUDIT_OWNER]
END
CREATE TABLE [dbo].[WORKPLACE_AUDIT_OWNER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
    [AuditQuestionID] [int] NOT NULL,
	[OWNER] [varchar](50) NOT NULL,
	[WhatToDo] [varchar](100) NOT NULL,
	[WhenToDo] [varchar](50) NOT NULL)
GO


