USE [AIDE]
GO

/****** Object:  Table [dbo].[COMCELL_CLOCK]    Script Date: 5/27/2019 2:37:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMCELL_CLOCK](
	[CLOCK_ID] [int] IDENTITY(1,1) NOT NULL,
	[CLOCK_DAY] [int] NOT NULL,
	[CLOCK_HOUR] [int] NOT NULL,
	[CLOCK_MINUTE] [int] NOT NULL,
	[EMP_ID] [int] NOT NULL
PRIMARY KEY CLUSTERED 
(
	[CLOCK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


