USE [AIDE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'OPTION_FUNCTION')
BEGIN
	DROP TABLE [dbo].[OPTION_FUNCTION]
END

CREATE TABLE [dbo].[OPTION_FUNCTION](
	[FunctionID] [int] IDENTITY(1,1) NOT NULL,
	[Description] varchar(255) NOT NULL
 CONSTRAINT [PK_OPTION_FUNCTION] PRIMARY KEY CLUSTERED 
(
	[FunctionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


