USE [AIDE]
GO

/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 07/10/2019 2:03:54 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CONTRIBUTORS](
	[CONTRI_ID] [int] NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[EMP_ID] [int] NOT NULL,
	[CONTRI_LVL] [varchar](10) NOT NULL
)


GO

SET ANSI_PADDING OFF
GO


