USE [AIDE]
GO

/****** Object:  Table [dbo].[WEEKLY_REPORT]    Script Date: 09/02/2019 1:53:26 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER TABLE WEEKLY_REPORT
ADD WR_TASK_ID INT,
    WR_DELETE_FG SMALLINT
	CONSTRAINT WEEKLY_DELETE_COL
		DEFAULT(0)
	WITH VALUES

GO


