USE [AIDE]
GO

/****** Object:  StoredProcedure [dbo].[sp_GetProjectByEmployeeList]    Script Date: 11/06/2019 3:02:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[sp_GetProjectByEmployeeList]
@Emp_ID int = null
AS

DECLARE @TEMPTABLE TABLE([STATUS] INT, EMP_ID INT)

SELECT	DISTINCT
		S.[DESCR] AS [STATUS],
		COALESCE(E.LAST_NAME +', ','') + E.FIRST_NAME  AS Name,
		FirstMonth = STUFF((SELECT ', ' + P.PROJ_NAME FROM PROJECT P, ASSIGNED_PROJECTS A
								WHERE E.EMP_ID = A.EMP_ID AND P.PROJ_ID = A.PROJ_ID AND MONTH(A.START_PERIOD) <= MONTH(GETDATE()) AND MONTH(A.END_PERIOD) >= MONTH(GETDATE())
								FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, ''),
		SecondMonth = STUFF((SELECT ', ' + P.PROJ_NAME FROM PROJECT P, ASSIGNED_PROJECTS A
								WHERE E.EMP_ID = A.EMP_ID AND P.PROJ_ID = A.PROJ_ID AND (MONTH(A.START_PERIOD) <= (MONTH(GETDATE())+1)) AND MONTH(A.END_PERIOD) >= (MONTH(GETDATE())+1)
								FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, ''),
		ThirdMonth = STUFF((SELECT ', ' + P.PROJ_NAME FROM PROJECT P, ASSIGNED_PROJECTS A
								WHERE E.EMP_ID = A.EMP_ID AND P.PROJ_ID = A.PROJ_ID AND (MONTH(A.START_PERIOD) <= (MONTH(GETDATE())+2)) AND MONTH(A.END_PERIOD) >= (MONTH(GETDATE())+2)
								FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 1, '')
FROM [EMPLOYEE]  E
LEFT JOIN [ATTENDANCE] AS A ON A.EMP_ID = E.EMP_ID
LEFT JOIN @TEMPTABLE AS T ON T.EMP_ID = E.EMP_ID
LEFT JOIN [STATUS] AS S ON S.[STATUS] = T.[STATUS] AND S.STATUS_ID = 1
WHERE E.DEPT_ID = (SELECT A.DEPT_ID FROM EMPLOYEE A INNER JOIN CONTACTS B
				   ON A.EMP_ID = B.EMP_ID WHERE A.EMP_ID = @Emp_ID) AND
	  E.DIV_ID = (SELECT A.DIV_ID FROM EMPLOYEE A INNER JOIN CONTACTS B
				   ON A.EMP_ID = B.EMP_ID WHERE A.EMP_ID = @Emp_ID) AND E.ACTIVE <> 2
GO


