USE [AIDE]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[sp_InsertProblemImplement]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[sp_InsertProblemImplement]
GO

CREATE PROCEDURE [dbo].[sp_InsertProblemImplement]
	@PROBLEM_ID INT,
	@OPTION_ID INT,
	@IMPLEMENT_DESCR VARCHAR(255),
	@IMPLEMENT_ASSIGNEE INT,
	@IMPLEMENT_VALUE VARCHAR(255) 

AS

INSERT [dbo].[PROBLEM_IMPLEMENT]
(
	[PROBLEM_ID],
	[OPTION_ID],
	[IMPLEMENT_DESCR],
	[IMPLEMENT_ASSIGNEE],
	[IMPLEMENT_VALUE]
)
VALUES
(
	@PROBLEM_ID,
	@OPTION_ID,
	@IMPLEMENT_DESCR,
	@IMPLEMENT_ASSIGNEE,
	@IMPLEMENT_VALUE
)




GO
