USE [AIDE]
GO
/****** Object:  StoredProcedure [dbo].[UpdateCheckAuditQuestionStatus]    Script Date: 6/17/2019 7:31:08 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:           <Author,,Name>
-- Create date: <Create Date,,>
-- Description:      <Description,,>
-- =============================================


IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND OBJECT_ID = OBJECT_ID('dbo.UpdateCheckAuditQuestionStatus'))
    BEGIN
        DROP PROCEDURE [dbo].UpdateCheckAuditQuestionStatus
    END
GO

CREATE PROCEDURE [dbo].[UpdateCheckAuditQuestionStatus]
       -- Add the parameters for the stored procedure here
  @DT_CHECK_FLG INT,
  @DT_CHECKED DATETIME,
  @AUDIT_QUESTIONS_ID INT,
  @FY_WEEK INT,
  @AUDIT_DAILY_ID INT,
  @WEEKDATE DATE,
  @AUDIT_GROUP_QUESTION INT
AS
BEGIN

       SET NOCOUNT ON;
	   IF @AUDIT_GROUP_QUESTION = 1
		BEGIN
		UPDATE WORKPLACE_AUDIT_DAILY 
				SET DT_CHECK_FLG = @DT_CHECK_FLG,
					DT_CHECKED = @DT_CHECKED 
			WHERE AUDIT_QUESTIONS_ID = @AUDIT_QUESTIONS_ID AND FY_WEEK = @FY_WEEK and AUDIT_DAILY_ID = @AUDIT_DAILY_ID
		

			UPDATE WORKPLACE_AUDIT_DAILY 
				SET DT_CHECKED = @DT_CHECKED 
			WHERE  WEEKDATE = @WEEKDATE AND FY_WEEK = @FY_WEEK
		END
		ELSE IF @AUDIT_GROUP_QUESTION = 2
			BEGIN
			UPDATE WORKPLACE_AUDIT_WEEKLY
					SET DT_CHECK_FLG = @DT_CHECK_FLG,
						DT_CHECKED = @DT_CHECKED 
				WHERE AUDIT_QUESTIONS_ID = @AUDIT_QUESTIONS_ID AND FY_WEEK = @FY_WEEK and AUDIT_WEEKLY_ID = @AUDIT_DAILY_ID
		

				UPDATE WORKPLACE_AUDIT_WEEKLY 
					SET DT_CHECKED = @DT_CHECKED 
				WHERE  WEEKDATE = @WEEKDATE AND FY_WEEK = @FY_WEEK
			END
		ELSE IF @AUDIT_GROUP_QUESTION = 3
			BEGIN
			UPDATE WORKPLACE_AUDIT_MONTHLY
					SET DT_CHECK_FLG = @DT_CHECK_FLG,
						DT_CHECKED = @DT_CHECKED 
				WHERE AUDIT_QUESTIONS_ID = @AUDIT_QUESTIONS_ID AND FY_WEEK = @FY_WEEK and AUDIT_MONTHLY_ID = @AUDIT_DAILY_ID
		

				UPDATE WORKPLACE_AUDIT_MONTHLY 
					SET DT_CHECKED = @DT_CHECKED 
				WHERE  WEEKDATE = @WEEKDATE AND FY_WEEK = @FY_WEEK
			END
		ELSE IF @AUDIT_GROUP_QUESTION = 4
			BEGIN
			UPDATE WORKPLACE_AUDIT_QUARTERLY
					SET DT_CHECK_FLG = @DT_CHECK_FLG,
						DT_CHECKED = @DT_CHECKED 
				WHERE AUDIT_QUESTIONS_ID = @AUDIT_QUESTIONS_ID AND FY_WEEK = @FY_WEEK and AUDIT_QUARTERLY_ID = @AUDIT_DAILY_ID
		

				UPDATE WORKPLACE_AUDIT_QUARTERLY 
					SET DT_CHECKED = @DT_CHECKED 
				WHERE  WEEKDATE = @WEEKDATE AND FY_WEEK = @FY_WEEK
			END
     SET NOCOUNT OFF;
END

GO
