USE AIDE
GO 

DELETE STATUS WHERE STATUS_NAME = 'SEVERITY'

INSERT INTO STATUS VALUES (13, 'SEVERITY', 'Low', 1)
INSERT INTO STATUS VALUES (13, 'SEVERITY', 'Medium', 2)
INSERT INTO STATUS VALUES (13, 'SEVERITY', 'High', 3)
INSERT INTO STATUS VALUES (13, 'SEVERITY', 'Critical', 4)