USE [AIDE]
GO

/****** Object:  Table [dbo].[SEND_CODE_CONFIG]    Script Date: 6/10/2019 2:25:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SEND_CODE_CONFIG](
	[SC_ID] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[SC_SENDER_EMAIL] [varchar](max) NOT NULL,
	[SC_SUBJECT] [varchar](max) NOT NULL,
	[SC_BODY] [varchar](max) NULL,
	[SC_PORT] [int] NOT NULL,
	[SC_HOST] [varchar](max) NOT NULL,
	[SC_ENABLE_SSL] INT NOT NULL,
	[SC_TIMEOUT] [int] NOT NULL,
	[SC_USE_DFLT_CREDENTIALS] INT NULL,
	[SC_SENDER_PASSWORD] [varchar](max) NULL,
	[SC_PASSWORD_EXPIRY] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


