USE [AIDE]
GO

/****** Object:  Table [dbo].[WEEK_RANGE]    Script Date: 5/14/2019 11:11:52 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WEEK_RANGE](
	[WEEK_ID] [int] IDENTITY(1,1) NOT NULL,
	[WEEK_START] [DATE] NOT NULL,
	[WEEK_END] [DATE] NOT NULL,
 CONSTRAINT [PK_WEEK_RANGE] PRIMARY KEY CLUSTERED 
(
	[WEEK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


